- name: Install basic packages
  package:
    name: ['wget','unzip','curl','systemd',]
    state: present
    update_cache: yes

- name: Ensure the system can use the HTTPS transport for APT.
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport

- name: Install APT HTTPS transport.
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes
  when: not apt_https_transport.stat.exists

- name: Nginx dependencies ...
  package: name=nginx state=present
  notify:
    - Restart nginx

- name: Install passlib (required for writing htpasswd file)...
  apt:
    name: python3-passlib
    state: installed

- name: Create htpasswd file to restrict access to vault web interface...
  htpasswd:
    name: "{{ USERNAME_FOR_VAULT }}"
    password: "{{ KIBANA_PASSWORD }}"
    path: /etc/nginx/htpasswd.users

- name: Copy default file of nginx file
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
  when: ansible_service_mgr == "systemd"
  become: yes

- name: Copy default file of nginx file
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-enabled/default
  when: ansible_service_mgr == "systemd"
  become: yes
  notify:
    - Restart nginx


