---

- name: copy ssh-config in ansible directory  file
  template:
    src: templates/config.j2
    dest: /etc/ansible/config
  when: ansible_service_mgr == "systemd"
  become: yes

- name: copy host or inventory  file
  template:
    src: templates/hosts.j2
    dest: /etc/ansible/hosts
  when: ansible_service_mgr == "systemd"
  become: yes

- name: copy ansible file
  template:
    src: templates/Ansible.j2
    dest: /etc/ansible/Ansible
  when: ansible_service_mgr == "systemd"
  become: yes

